[package]
name = "mrvn-back-ytdl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0"
futures = "0.3"
url = "2.2"
youtube_dl = "0.6"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["cache", "client", "gateway", "rustls_backend", "model", "unstable_discord_api", "voice"]

[dependencies.songbird]
version = "0.2"
features = ["gateway", "serenity-rustls"]

[dependencies.tokio]
version = "1.10"
features = ["macros", "rt-multi-thread"]
