[package]
name = "mrvn-front-discord"
version = "0.1.0"
edition = "2018"

[dependencies]
mrvn-model = { path = "../mrvn-model" }
mrvn-back-ytdl = { path = "../mrvn-back-ytdl" }
dotenv = "0.15"
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
serde = "1.0"
serde_json = "1.0"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["cache", "client", "gateway", "rustls_backend", "model", "unstable_discord_api", "voice"]

[dependencies.tokio]
version = "1.10"
features = ["macros", "rt-multi-thread"]
